/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Hadith = IDL.Record({
  'topic' : IDL.Text,
  'collection' : IDL.Text,
  'arabicText' : IDL.Text,
  'narrator' : IDL.Text,
  'englishTranslation' : IDL.Text,
});
export const KnowledgeArticle = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const QuranVerse = IDL.Record({
  'surahNumber' : IDL.Nat,
  'verseNumber' : IDL.Nat,
  'surahName' : IDL.Text,
  'transliteration' : IDL.Text,
  'arabicText' : IDL.Text,
  'englishTranslation' : IDL.Text,
});
export const IslamicEvent = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'hijriDate' : IDL.Text,
  'gregorianDate' : IDL.Text,
});
export const PrayerTime = IDL.Record({ 'name' : IDL.Text, 'time' : IDL.Text });

export const idlService = IDL.Service({
  'addHadith' : IDL.Func([Hadith], [IDL.Nat], []),
  'addKnowledgeArticle' : IDL.Func([KnowledgeArticle], [IDL.Nat], []),
  'addQuranVerse' : IDL.Func([QuranVerse], [IDL.Nat], []),
  'getAllHadiths' : IDL.Func([], [IDL.Vec(Hadith)], ['query']),
  'getAllIslamicEvents' : IDL.Func([], [IDL.Vec(IslamicEvent)], ['query']),
  'getAllKnowledgeArticles' : IDL.Func(
      [],
      [IDL.Vec(KnowledgeArticle)],
      ['query'],
    ),
  'getAllPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
  'getAllQuranVerses' : IDL.Func([], [IDL.Vec(QuranVerse)], ['query']),
  'getDailyVerse' : IDL.Func([], [QuranVerse], ['query']),
  'getHadith' : IDL.Func([IDL.Nat], [IDL.Opt(Hadith)], ['query']),
  'getIslamicEvent' : IDL.Func([IDL.Nat], [IDL.Opt(IslamicEvent)], ['query']),
  'getKnowledgeArticle' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(KnowledgeArticle)],
      ['query'],
    ),
  'getPrayerTime' : IDL.Func([IDL.Nat], [IDL.Opt(PrayerTime)], ['query']),
  'getQuranVerse' : IDL.Func([IDL.Nat], [IDL.Opt(QuranVerse)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Hadith = IDL.Record({
    'topic' : IDL.Text,
    'collection' : IDL.Text,
    'arabicText' : IDL.Text,
    'narrator' : IDL.Text,
    'englishTranslation' : IDL.Text,
  });
  const KnowledgeArticle = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const QuranVerse = IDL.Record({
    'surahNumber' : IDL.Nat,
    'verseNumber' : IDL.Nat,
    'surahName' : IDL.Text,
    'transliteration' : IDL.Text,
    'arabicText' : IDL.Text,
    'englishTranslation' : IDL.Text,
  });
  const IslamicEvent = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'hijriDate' : IDL.Text,
    'gregorianDate' : IDL.Text,
  });
  const PrayerTime = IDL.Record({ 'name' : IDL.Text, 'time' : IDL.Text });
  
  return IDL.Service({
    'addHadith' : IDL.Func([Hadith], [IDL.Nat], []),
    'addKnowledgeArticle' : IDL.Func([KnowledgeArticle], [IDL.Nat], []),
    'addQuranVerse' : IDL.Func([QuranVerse], [IDL.Nat], []),
    'getAllHadiths' : IDL.Func([], [IDL.Vec(Hadith)], ['query']),
    'getAllIslamicEvents' : IDL.Func([], [IDL.Vec(IslamicEvent)], ['query']),
    'getAllKnowledgeArticles' : IDL.Func(
        [],
        [IDL.Vec(KnowledgeArticle)],
        ['query'],
      ),
    'getAllPrayerTimes' : IDL.Func([], [IDL.Vec(PrayerTime)], ['query']),
    'getAllQuranVerses' : IDL.Func([], [IDL.Vec(QuranVerse)], ['query']),
    'getDailyVerse' : IDL.Func([], [QuranVerse], ['query']),
    'getHadith' : IDL.Func([IDL.Nat], [IDL.Opt(Hadith)], ['query']),
    'getIslamicEvent' : IDL.Func([IDL.Nat], [IDL.Opt(IslamicEvent)], ['query']),
    'getKnowledgeArticle' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(KnowledgeArticle)],
        ['query'],
      ),
    'getPrayerTime' : IDL.Func([IDL.Nat], [IDL.Opt(PrayerTime)], ['query']),
    'getQuranVerse' : IDL.Func([IDL.Nat], [IDL.Opt(QuranVerse)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };