/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Hadith {
  'topic' : string,
  'collection' : string,
  'arabicText' : string,
  'narrator' : string,
  'englishTranslation' : string,
}
export interface IslamicEvent {
  'name' : string,
  'description' : string,
  'hijriDate' : string,
  'gregorianDate' : string,
}
export interface KnowledgeArticle {
  'title' : string,
  'content' : string,
  'summary' : string,
  'category' : string,
}
export interface PrayerTime { 'name' : string, 'time' : string }
export interface QuranVerse {
  'surahNumber' : bigint,
  'verseNumber' : bigint,
  'surahName' : string,
  'transliteration' : string,
  'arabicText' : string,
  'englishTranslation' : string,
}
export interface _SERVICE {
  'addHadith' : ActorMethod<[Hadith], bigint>,
  'addKnowledgeArticle' : ActorMethod<[KnowledgeArticle], bigint>,
  'addQuranVerse' : ActorMethod<[QuranVerse], bigint>,
  'getAllHadiths' : ActorMethod<[], Array<Hadith>>,
  'getAllIslamicEvents' : ActorMethod<[], Array<IslamicEvent>>,
  'getAllKnowledgeArticles' : ActorMethod<[], Array<KnowledgeArticle>>,
  'getAllPrayerTimes' : ActorMethod<[], Array<PrayerTime>>,
  'getAllQuranVerses' : ActorMethod<[], Array<QuranVerse>>,
  'getDailyVerse' : ActorMethod<[], QuranVerse>,
  'getHadith' : ActorMethod<[bigint], [] | [Hadith]>,
  'getIslamicEvent' : ActorMethod<[bigint], [] | [IslamicEvent]>,
  'getKnowledgeArticle' : ActorMethod<[bigint], [] | [KnowledgeArticle]>,
  'getPrayerTime' : ActorMethod<[bigint], [] | [PrayerTime]>,
  'getQuranVerse' : ActorMethod<[bigint], [] | [QuranVerse]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];